name: clean artifacts

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: cleanup
        uses: glassechidna/artifact-cleaner@430d9257d21e295fd5c7ffe4449c2b6dd4fb5423 # v2
        with:
          minimumAge: 172800 # all artifacts 2 days